### ISSUE TITLE
Multiple services with different names use the config values from the last defined service

### ISSUE THREAD

**Issue by ALERTua** [hasscc/hass-edge-tts#33]
Defining:
```
tts:
  - platform: edge_tts
    service_name: edge_say
    language: en-US-ChristopherNeural

  - platform: edge_tts
    service_name: edge_say_ua
    language: uk-UA-PolinaNeural
```
Creates two services with the provided names correctly, but calling `tts.edge_say` uses the voice from `edge_say_ua`.
The config values should be different for each defined service.
