### ISSUE TITLE
configruation修改后无法重启

### ISSUE THREAD

**Issue by iapYang** [hasscc/hass-edge-tts#42]
```yaml
# Text to speech
tts:
  - platform: google_translate
  - platform: edge_tts
    service_name
    language: zh-CN # Default language or voice (Optional)
```

在configuration.yaml中修改为这样，然后在开发者工具中重启，就会卡住

ha版本：2023.8.0
